name: "Runs some tests"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: "windows-latest"
    env:
      PRODUCT_VERSION: ${{ github.ref_name }}

    steps:
      - name: "Test for webview"
        shell: "pwsh"
        run: |-
          if (Test-Path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}") { Write-Host "Registry key exists." } else { Write-Host "Registry key does not exist." }
