name: "Runs some tests"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: "windows-latest"
    env:
      PRODUCT_VERSION: ${{ github.ref_name }}

    steps:
      - name: "Print variable"
        shell: "cmd"
        run: |-
          echo ${{ vars.MY_VARIABLE }}
