name: "Runs some tests"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: "windows-latest"
    env:
      PRODUCT_VERSION: ${{ github.ref_name }}

    steps:
      - name: "Add to path"
        shell: "cmd"
        run: |-
          echo C:\msys64\mingw64\bin>> %GITHUB_PATH%
          echo C:\msys64\mingw32\bin>> %GITHUB_PATH%

      - name: "Echo path"
        shell: "cmd"
        run: |-
          echo %PATH%
