name: "Runs some tests"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: "windows-latest"
    env:
      PRODUCT_VERSION: ${{ github.ref_name }}

    steps:
      - name: "Print rust targets"
        shell: "cmd"
        run: |-
          rustup toolchain list

      - name: "Test JSON presence perl"
        shell: "perl {0}"
        run: |-
          use JSON;
