name: "Runs some tests"
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: "windows-latest"
    env:
      PRODUCT_VERSION: ${{ github.ref_name }}

    steps:
      - name: "Print PWD"
        shell: "cmd"
        run: |
          echo PWD %CD%

      - name: "Print Version"
        shell: "cmd"
        run: |
          echo version %PRODUCT_VERSION%
